version: "3"

services:
  api:
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: client
    volumes:
      - ./client:/frontend
      - node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:10.5
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=campsite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'

volumes:
  node_modules:
